--
-- PostgreSQL database dump
--

-- Dumped from database version 11.7 (Debian 11.7-0+deb10u1)
-- Dumped by pg_dump version 11.7 (Debian 11.7-0+deb10u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: heros; Type: TABLE; Schema: public; Owner: ftm
--

CREATE TABLE public.heros (
    id integer NOT NULL,
    heroname character varying,
    heroage integer,
    heropower character varying,
    heroweakness character varying,
    squadid integer,
    avatarurl character varying
);


ALTER TABLE public.heros OWNER TO ftm;

--
-- Name: heros_id_seq; Type: SEQUENCE; Schema: public; Owner: ftm
--

ALTER TABLE public.heros ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.heros_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: squads; Type: TABLE; Schema: public; Owner: ftm
--

CREATE TABLE public.squads (
    id integer NOT NULL,
    squadname character varying,
    squadcause character varying,
    maxsize integer,
    squadfull boolean
);


ALTER TABLE public.squads OWNER TO ftm;

--
-- Name: squads_id_seq; Type: SEQUENCE; Schema: public; Owner: ftm
--

ALTER TABLE public.squads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.squads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: heros; Type: TABLE DATA; Schema: public; Owner: ftm
--

COPY public.heros (id, heroname, heroage, heropower, heroweakness, squadid, avatarurl) FROM stdin;
1	Ironman	30	Genius Level Intellect	Swimming	1	https://www.pixel4k.com/wp-content/uploads/2019/09/ironman_1568055212.jpg
2	Dr Strange	35	Magic Mastery 	Love	1	https://images.hdqwalls.com/download/2020-doctor-strange-4k-8v-3840x2400.jpg
\.


--
-- Data for Name: squads; Type: TABLE DATA; Schema: public; Owner: ftm
--

COPY public.squads (id, squadname, squadcause, maxsize, squadfull) FROM stdin;
1	Avengers	Save The planet from Thanos	4	\N
\.


--
-- Name: heros_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ftm
--

SELECT pg_catalog.setval('public.heros_id_seq', 2, true);


--
-- Name: squads_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ftm
--

SELECT pg_catalog.setval('public.squads_id_seq', 1, true);


--
-- Name: heros heros_pkey; Type: CONSTRAINT; Schema: public; Owner: ftm
--

ALTER TABLE ONLY public.heros
    ADD CONSTRAINT heros_pkey PRIMARY KEY (id);


--
-- Name: squads squads_pkey; Type: CONSTRAINT; Schema: public; Owner: ftm
--

ALTER TABLE ONLY public.squads
    ADD CONSTRAINT squads_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

